### ISSUE TITLE
Improve README.md with examples on how to run it

### ISSUE THREAD

**Issue by lucianoratamero** [PeRDy/starlette-api#4]
Hey, folks! :]

It would be great if we had a basic example on how to run this, so it's easier to jump into and contribute as well.
If I have the time, I can do it, but if someone had that already set up, it would be nice!

Thanks!

**Comment by PeRDy** [comment]
Hey !

I'm a bit more on getting something ready as soon as possible, so if anyone want to help with that it would be awesome :)

**Comment by Lynskylate** [comment]
I think you should create a base doc structure so that we can provide documentation.

**Comment by PeRDy** [comment]
We have a more detailed README with a full example and I'll build a proper docs site once I have some free time.
